### PR TITLE
Cheshirekow/sphinx20

### PR DESCRIPTION
**Pull request by cheshirekow**
This is an incremental patch on top of #156 . Using this branch the following works with sphinx 2.0.1
```
$ hieroglyph -q --title Hello --author Me --slide-theme single-level .
$ make slides
```

### CODE REVIEW

**Comment by oliver-sanders** [comment]
Looks good, works!

Rebasing on top of #158 there are only a few test failures left (Sphinx 2.0.1):

```
======================================================================
ERROR: test_nextslide_allows_explicit_title (hieroglyph.tests.test_directives.NextSlideTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "~/hieroglyph.git/.eggs/sphinx_testing-1.0.1-py3.7.egg/sphinx_testing/util.py", line 171, in decorator
    return func(*(args + (app, status, warning)), **kwargs)
  File "~/hieroglyph.git/src/hieroglyph/tests/test_directives.py", line 341, in test_nextslide_allows_explicit_title
    second_title = inner_html(slides[1].find('h2'))
IndexError: list index out of range

======================================================================
ERROR: test_quickstart (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_quickstart
Traceback (most recent call last):
  File "~/pyenv/lib/python3.7/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "~/hieroglyph.git/src/hieroglyph/tests/test_quickstart.py", line 10, in <module>
    from sphinx import quickstart as sphinx_quickstart
ImportError: cannot import name 'quickstart' from 'sphinx' (~/pyenv/lib/python3.7/site-packages/sphinx/__init__.py)


======================================================================
FAIL: test_slide (hieroglyph.tests.test_directives.SlideTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "~/hieroglyph.git/src/hieroglyph/tests/test_directives.py", line 84, in test_slide
    u'Heading',
AssertionError: 'No Directive Entry For "Slide" In Module [77 chars]ame.' != 'Heading'
+ Heading- No Directive Entry For "Slide" In Module "Docutils.Parsers.Rst.Languages.En".
- Trying "Slide" As Canonical Directive Name.

======================================================================
FAIL: test_slide_without_content (hieroglyph.tests.test_directives.SlideTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "~/hieroglyph.git/src/hieroglyph/tests/test_directives.py", line 107, in test_slide_without_content
    'slide',
AssertionError: 'system_message' != 'slide'
- system_message
+ slide


======================================================================
FAIL: test_slide_without_title (hieroglyph.tests.test_directives.SlideTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "~/hieroglyph.git/src/hieroglyph/tests/test_directives.py", line 134, in test_slide_without_title
    'slide',
AssertionError: 'system_message' != 'slide'
- system_message
+ slide


----------------------------------------------------------------------
Ran 51 tests in 6.064s

FAILED (failures=3, errors=2)
Test failed: <unittest.runner.TextTestResult run=51 errors=2 failures=3>
error: Test failed: <unittest.runner.TextTestResult run=51 errors=2 failures=3>
```

**Comment by nyergler** [comment]
Apologies for letting this linger, @cheshirekow. I believe these changes have been merged as part of @oliver-sanders PRs. I'm still not sure that the format can be safely changed (see comments on #156). I'm going to close this, but please comment/re-open if I've missed something that needs to be applied.

**Comment by cheshirekow** [comment]
No worries @nyergler. The one thing I didn't see in the recently merge PRs is the change to `sphinx.cmd.quickstart`... but maybe I missed that. If that got pulled in then I don't think there is anything left in this MR that needs merging.

**Comment by lpirl** [comment]
@cheshirekow as in e61ae1a4a ?

**Comment by cheshirekow** [comment]
Ah, there it is. Yup, looks good then. Carry on.
